# Generated by Django 4.2.7 on 2024-07-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('phone_number', models.CharField(max_length=13)),
                ('telegram_link', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='image_bb')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tariflar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comapny', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('eating', models.IntegerField()),
                ('viza', models.IntegerField()),
                ('medical', models.CharField(max_length=255)),
                ('tajriba', models.CharField(max_length=255)),
                ('suv', models.IntegerField()),
            ],
        ),
    ]
