# Generated by Django 4.2.7 on 2024-07-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tariflar_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariflar',
            name='viza',
            field=models.BooleanField(),
        ),
    ]
